version: '3.8'
services:
  database:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment: 
      - MYSQL_DATABASE=blogsdb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'